export const VIDEO_LIST_ACTION = {
  FETCH_VIDEO_LIST_START: "FETCH_VIDEO_LIST_START",
  FETCH_VIDEO_LIST_SUCCESS: "FETCH_VIDEO_LIST_SUCCESS",
  FETCH_VIDEO_LIST_FAILURE: "FETCH_VIDEO_LIST_FAILURE",
  SET_SELECTED_VIDEO: "SET_SELECTED_VIDEO",
};
